### ISSUE TITLE
Downloading more that 7 Episodes Error

### ISSUE THREAD

**Issue by jeffwrusso** [KevCui/soap2day-dl#1]
Great work!  I noticed something after I got this up and running on a Ubuntu laptop.

If you download more than 7 episode you get an error message stating:
parse error: Invalid numeric literal at line 1, column 10

**Comment by KevCui** [comment]
Hi @jeffwrusso, what's the TV series name you were downloading? Which episodes? If you would like to share those info, it will help me for the further debugging.

**Comment by KevCui** [comment]
Ok, I find the root cause. It should be fixed in the latest commit.
