### ISSUE TITLE
curl: (6)Could not resolve host: d3.wewon.to

### ISSUE THREAD

**Issue by luggi83** [KevCui/soap2day-dl#11]
Since two days ago, any download requests fail with the error message from the title. Downloading from soap2day with getting the links directly works fine...

**Comment by KevCui** [comment]
Hi @luggi83, it looks like the server hosting the media resource is currently down. Nothing can be watched on the site either. :man_shrugging:

**Comment by KevCui** [comment]
Well, host domain is expired recentdly: https://www.whois.com/whois/wewon.to
`Expires on:           Thu Dec 23 19:24:13 2021`

**Comment by luggi83** [comment]
Just a quick heads-up: In my corner of the world, soap2day now uses q14.mrqls.to (Movies) and f4.mrqls.to (Series) to serve content. After swapping out these hosts in the script, everything works again. I'd do a commit but have no clue how. Again, thanks for the great tool!

**Comment by KevCui** [comment]
Thanks @luggi83 for the info. I'll take a look later.
