### ISSUE TITLE
Cookie

### ISSUE THREAD

**Issue by Cybersecghost** [KevCui/soap2day-dl#13]
I am keep getting [ERROR] Cannot get cookie. Try again later.

Can someone please help me with this.

**Comment by KevCui** [comment]
Hi @Cybersecghost, the script cannot fetch cookies any more due to the server restriction. A new method needs to be implemented. Until then, the script is no longer working.  :(

**Comment by KevCui** [comment]
Hi @Cybersecghost, the latest commit should fix the cookie issue. From now on, some new dependencies are required, please check readme file for more details. Please give it a try.

**Comment by Cybersecghost** [comment]
Thank you very much, I will give it a try.

**Comment by Cybersecghost** [comment]
Hi,

 

I have try to follow your instructions but nothing is working.

Can you please maybe give me a step by step guide. I am still a noob with linux.

Thank you much appreciate it.

**Comment by KevCui** [comment]
Hi @Cybersecghost, no worry. Could you share more details about which error you occur? I can then take a look.

**Comment by KevCui** [comment]
@Cybersecghost step by step, sure:

1. Check dependencies if they are all installed on your machine https://github.com/KevCui/soap2day-dl#dependency
2. Install `puppeteer` https://github.com/KevCui/soap2day-dl#installation
3. Run script `./soap2day-dl.sh -n 'game of'`

It should work like a charm. Let me know if something blocks you.

**Comment by Cybersecghost** [comment]
So I try it again and this is the error I get.

/soap2day-dl.sh: line 185: /opt/soap2day-dl//.source.html: Permission denied

 

So if I run it with sudo then I get cannot fetch cookie.

 

I also see there is not a source.list file.

 

Can you please help me

**Comment by KevCui** [comment]
Hi @Cybersecghost, a normal user is enough to run the script, you don't need to use root or sudo, i's also not recommended. 

I saw your put script under `/opt/`. I'd suggest to clone the repo to `/home/{your_user_name}/`, so that your user has to permission to create `.source.html` file.

**Comment by Cybersecghost** [comment]
Hi, will try that and let you know.

 

Thank you for the support

**Comment by KevCui** [comment]
Ok, seems media name is empty, weird. Would you mind to run script with the flag `-d`? It will print all debug logs. Paste some logs here and I'll take another look.

**Comment by Papa-Gandhi** [comment]
Hey Kevin, I tried using the script, I downloaded all the code and dependencies, but I still get this:

./soap2day-dl.sh: line 34: : command not found
/usr/bin/chrome
[INFO] Fetching cookie...
[ERROR] Cannot get cookie. Try again later.

Please help.

**Comment by KevCui** [comment]
Hi @Papa-Gandhi, it looks like you don't have Chromium or Chrome on your machine, please install one. After that, the script should work.

**Comment by Papa-Gandhi** [comment]
I do have it, on the raspberry pi

**Comment by KevCui** [comment]
@Papa-Gandhi Ok, run `which chrome` in your terminal, see the path? If not, try to put chrome binary in `/usr/bin`, should work.

**Comment by Papa-Gandhi** [comment]
it worked, after some coding
line 114 should be 

echo "/usr/bin/chromium-browser"


 instead of 


echo "/usr/bin/chrome"

**Comment by Cybersecghost** [comment]
Hi,

 

I am getting this error now.

 

tee: /home/ubuntu/soap2day-dl/search.list: Permission denied

**Comment by Cybersecghost** [comment]
Mine is also working now finally.

 

I went and change the whole directory permission to chmod a+rwx

**Comment by KevCui** [comment]
Hi @Papa-Gandhi, Hi @Cybersecghost, thank you for sharing your solutions! Good to know it works for both of you :)
