### ISSUE TITLE
Media not found!

### ISSUE THREAD

**Issue by lfoliveira317** [KevCui/soap2day-dl#15]
when I tried to use the script using the -n or -p parameters.

**Comment by lfoliveira317** [comment]
Right now when we make the request its was redirected to the page https://soap2day.ac/enter.html?r=1

**Comment by KevCui** [comment]
Hi @lfoliveira317, please run command with flag `-d` to enable debug mode. It will help to see what went wrong.

**Comment by KevCui** [comment]
Hi @lfoliveira317, I made some changes. Give the latest commit a try. If you still occur the same issue, please run command with `-d` and paste logs here, I will take a look.
