### ISSUE TITLE
TypeError: page._client.send is not a function

### ISSUE THREAD

**Issue by MagnusStrom** [KevCui/soap2day-dl#19]
I just installed everythhinng annd got thhis, Any tips, on windows?

**Comment by KevCui** [comment]
Hey @MagnusStrom, thanks for reporting this issue. It appears to be an error from `puppeteer-extra-plugin-stealth`. But it doesn't stop the script, therefore, I updated the code in the last commit to ignore this error. Please pull the change and give it a try.
