### ISSUE TITLE
Multi Episode Download Missing x.x0

### ISSUE THREAD

**Issue by jeffwrusso** [KevCui/soap2day-dl#2]
Just noticed when using an episode download range the episodes ending in 0 are missing from the downloads.  For example if you use -e 1.1-1.51 you will be missing 1.10,1.20,1.30,1.40,1.50.  I have not been able to test if it makes a difference if the the last digit in the range is a 0 if it makes a difference (example 1.1-1.50).

Thanks!

**Comment by KevCui** [comment]
Hi @jeffwrusso, good catch. The issue is fixed in the latest commit. Thanks.
