### ISSUE TITLE
Media Not Found (Again)

### ISSUE THREAD

**Issue by MagnusStrom** [KevCui/soap2day-dl#20]
Now that it works, Any show, even if it exists, shows media not found. Any tips??

**Comment by MagnusStrom** [comment]
Also, I cannot see terminal after it says this. It instantly closes

**Comment by KevCui** [comment]
Hey @MagnusStrom, would you mind sharing more details? Which command you entered to run the script? Try with `-d` flag in the end of the command, it will print out all debug logs. If you could paste some logs here, I can take a deeper look.

**Comment by KevCui** [comment]
Hey @MagnusStrom, it's been a month and there is no further information provided from your side. I assume you managed to make it work? So, I'm closing this issue for now. If you are still facing the same issue, please provide more details and logs in the comment or in a new issue, I will try to take another look.

**Comment by MagnusStrom** [comment]
Hello, I gave up and stuck with torrents but now I am back. I cannot provide copy paste logs as the program closes right after the error, but here is what i got from a clip.
![image](https://user-images.githubusercontent.com/80227480/187802495-228db53f-2fc6-4c62-9da5-a12d3687cfe3.png)

**Comment by KevCui** [comment]
Hey @MagnusStrom, could you please let me know which movie or TV you are trying to download with the script? Mind sharing the command you executed?

**Comment by MagnusStrom** [comment]
Hello, if I run ./soap2day-dl.sh, it does not run and says media not found, but if I run soap2day-dl.sh, it runs fine. Im assuming this is a certified windows moment.

**Comment by KevCui** [comment]
Hey @MagnusStrom,

> if I run ./soap2day-dl.sh, it does not run and says media not found, but if I run soap2day-dl.sh, it runs fine. Im assuming this is a certified windows moment. 

If it's an OS issue, I don't know how it could be fixed in the script... Moreover, it's not related to the error `Media not found` in your screenshot. I just want to know the name of media you used to download `-n <name>`. If you provide me the name, I can try it on my side.

**Comment by MagnusStrom** [comment]
It is related though. That screenshot happens when i do  ./soap2day-dl.sh -n "The Snoopy"

**Comment by KevCui** [comment]
Hey @MagnusStrom, the same media title works for me. From your logs, it looks like the fetched cookie is invalid. Unfortunately, the logs in your screenshot are incomplete, it doesn't pinpoint the exact error.

You could try to remove `cookie.json` in the script directory and run script again, it will generate a new file. If it's still not working, please paste the complete logs here and I will take another look.
