### ISSUE TITLE
Multiple connection

### ISSUE THREAD

**Issue by cyber-hunt7** [KevCui/soap2day-dl#25]
How can you use the script to run multiple connections like IDM, to download faster than 500kbps.

**Comment by KevCui** [comment]
Hey @cyber-hunt7, try use external downloader. You could get an example in README.md:

```

- Use external download utility instead of curl, for example using aria2c:

./soap2day-dl.sh -n 'game of thrones' -e 1.1 -x 'aria2c -x 16'
```

**Comment by cyber-hunt7** [comment]
Thank you very much it is very helpfull
