### ISSUE TITLE
parse error: Invalid numeric literal at line 2, column 6

### ISSUE THREAD

**Issue by jeffwrusso** [KevCui/soap2day-dl#3]
I noticed that script seems to be broken now.  It could be they changed something at the site because direct browsing still works for me.

It looks like the following line is throwing the "parse error: Invalid numeric literal at line 2, column 6"

`el="$($_JQ -r '.val' <<< "$d")"`

The HTML code below is what it is trying to parse.

`	<body style="text-align:center">
				
		<div class="content">
			<div class="container">
				<br>
				<div class="row">

					<div  style="width:50%;margin:0 auto">
						
						<div class="panel panel-default">
				
							<div class="panel-heading">Sorry, An unexpected error has occurred. Please try again. <a href ="\">Go back home</a></div>
						
						</div>
					</div>
				</div>
			</div>
			
		</div>
		
		<footer>
			<div class="container">
			<div class="row">
			<div class="col-sm-12 text-center">
			<h5>copyright @ SOAP2DAY.com</h5>
			</div>
			</div>
			</div>
		</footer>
			
	</body>
`

**Comment by KevCui** [comment]
@jeffwrusso Right, something is changed on the sever side. The latest commit should work.
