### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by atlcell** [KevCui/soap2day-dl#4]
This is Broken

After installing all packages and running the script, nothing is outputted into the console

no errors, no warnings, nothing

just nothing, no feedback from the script

**Comment by KevCui** [comment]
Hi @atlcell, could you try to run script with `bash -x` in front of you command, like: `bash -x ./soap2day-dl.sh`. This will display all logs for further debugging.

**Comment by atlcell** [comment]
```
Macs-Air:soap2day-dl mac$ bash -x ./soap2day-dl.sh
+ set -e
+ set -u
+ [[ ./soap2day-dl.sh == \.\/\s\o\a\p\2\d\a\y\-\d\l\.\s\h ]]
+ main
+ set_args
+ expr '' : '.*--help'
+ getopts :hlsn:p:e: opt
+ set_var
++ command -v curl
+ _CURL=/usr/bin/curl
++ command -v jq
+ _JQ=
```
![Screen Shot 2021-06-08 at 3 17 46 AM](https://user-images.githubusercontent.com/1452704/121140704-26bac500-c808-11eb-9aa7-4631d8cec94d.png)

**Comment by KevCui** [comment]
Hi @atlcell,

The log shows that `jq` is missing on your machine, you could find info here to install it https://stedolan.github.io/jq/download/

**Comment by atlcell** [comment]
installing with `brew` now, hold on

**Comment by atlcell** [comment]
still doesn't work, same output - nothing.  `jq` has been installed, its a json tool


![Screen Shot 2021-06-08 at 3 23 38 AM](https://user-images.githubusercontent.com/1452704/121141458-f7588800-c808-11eb-9173-33faad220c27.png)


```
==> Installing jq dependency: oniguruma
==> Pouring oniguruma--6.9.7.1.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/oniguruma/6.9.7.1: 14 files, 1.4MB
==> Installing jq
==> Pouring jq--1.6.mojave.bottle.1.tar.gz
🍺  /usr/local/Cellar/jq/1.6: 18 files, 1MB
Macs-Air:soap2day-dl mac$ npm i puppeteer-core puppeteer-extra puppeteer-extra-plugin-stealth commander
Macs-Air:soap2day-dl mac$ ./soap2day-dl.sh
Macs-Air:soap2day-dl mac$ bash -x ./soap2day-dl.sh
+ set -e
+ set -u
+ [[ ./soap2day-dl.sh == \.\/\s\o\a\p\2\d\a\y\-\d\l\.\s\h ]]
+ main
+ set_args
+ expr '' : '.*--help'
+ getopts :hlsn:p:e: opt
+ set_var
++ command -v curl
+ _CURL=/usr/bin/curl
++ command -v jq
+ _JQ=/usr/local/bin/jq
++ command -v pup
+ _PUP=
Macs-Air:soap2day-dl mac$
```

**Comment by atlcell** [comment]
I've installed `pup`

again, nothing

**Comment by atlcell** [comment]
'pup' is either stableware or abandonware

**Comment by atlcell** [comment]
@KevCui is this script actually still works for you, it would be great if you update it/troubleshoot with me some more

**Comment by KevCui** [comment]
Hi @atlcell it does work for me. What's your current problem? If you share me some logs, I may help you troubleshooting.

**Comment by KevCui** [comment]
Hi @atlcell, I made some changes in the script to better support MacOS, also added guide how to "add Chrome alias" in README.md. Hope this will for you.
