### ISSUE TITLE
Running the script just does nothing

### ISSUE THREAD

**Issue by MagnusStrom** [KevCui/soap2day-dl#5]
I'm on mac, and maybe I just installed the chrome thing wrong? I put it in the file and ran command -v chrome and nothing happened, and then I ran the script and nothing happened.

**Comment by KevCui** [comment]
Hi @MagnusStrom, so you tried try this?

```
4. If you are on MacOS, please add Chrome alias in ~/.bashrc or ~/.zshrc or other shell rc file:

alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
```
Restart terminal app and then run `command -v chrome`?

**Comment by MagnusStrom** [comment]
Running the second command worked, but the first one did not.

**Comment by MagnusStrom** [comment]
@KevCui And yes, I have tried that. I did:
`nano ~./bashrc` 
and got this https://i.imgur.com/kaTprf3.png

**Comment by KevCui** [comment]
Hi @MagnusStrom, you edited `~/.bashrc`, not `~./bashrc`, right? I think it's a typo in your previous comment.
Since Apple changed default shell to Zsh. By any chance, you are not using Bash? You can check you current shell with this command `echo $SHELL`. If it's Zsh, you have to add alias into `~/.zshrc`.

**Comment by MagnusStrom** [comment]
Hello @KevCui, yes turns out i needed to edit `zshrc`. And running `command -v chrome` now gives me:
https://i.imgur.com/3r01CTh.png
But still running `./soap2day-dl.sh -n 'game of'`
gives me nothing!

**Comment by KevCui** [comment]
Hi @MagnusStrom, one step closer :) Could you run `bash -x ./soap2day-dl.sh -n 'game of'` and share the log? Thanks.

**Comment by MagnusStrom** [comment]
![image](https://user-images.githubusercontent.com/80227480/125084981-16f8ff80-e098-11eb-92b8-116b69cfba23.png)

**Comment by MagnusStrom** [comment]
Wait, I think I did install jq incorrectly, i have to install it through homebrew

**Comment by MagnusStrom** [comment]
![image](https://user-images.githubusercontent.com/80227480/125093561-6b07e200-e0a0-11eb-9873-16cd728343f9.png)
Update: Now it returns this.

**Comment by KevCui** [comment]
Hi @MagnusStrom, it's weird the chrome path is not recognized during script execution. I hard-coded it in the latest commit. It should work for you now.

**Comment by MagnusStrom** [comment]
it worked!! thank you!!
