### ISSUE TITLE
Downloads get stuck on "Fetching cookie"

### ISSUE THREAD

**Issue by spongyfan1** [KevCui/soap2day-dl#7]
![image](https://user-images.githubusercontent.com/89739177/131329141-76b709a1-9635-48d9-85ea-ec089597e85a.png)
It's just stuck on Fetching cookie. Running Ubuntu 21.04.

**Comment by KevCui** [comment]
Hi @spongyfan1, thanks for your report. The fix should work in the latest commit. Please quote the title like: `./soap2day-dl.sh -n 'the big bang theory'`
