### ISSUE TITLE
media not found?

### ISSUE THREAD

**Issue by MagnusStrom** [KevCui/soap2day-dl#8]
```
./soap2day-dl.sh: line 37: realpath: command not found
[INFO] Fetching cookie...
[ERROR] Media not found!
```

**Comment by KevCui** [comment]
Hi @MagnusStrom, `realpath` command is included in GNU coreutils. Please check if you have it installed on your system.

**Comment by KevCui** [comment]
@MagnusStrom Could you share the entire command you entered to run the script?

**Comment by MagnusStrom** [comment]
@KevCui ./soap2day-dl.sh -n 'rick and'

**Comment by KevCui** [comment]
@MagnusStrom Could you run `bash -x ./soap2day-dl.sh -n 'rick and'`? This will enable debug logs. If you could paste logs here, I will take a look.

**Comment by KevCui** [comment]
Close this issue for now. Once I got the necessary logs, I will take another look.
