### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by jorgeorejas** [KevCui/soap2day-dl#9]
There's some episodes that don't download correctly, I tried running with the `bash -x ./soap2day-dl.sh -n halt and catch fire` and when I paste the [output URL](https://f1.wewon.to/a/t1/halt-and-catch-fire/s01e06.mp4?tok=4D4F4B30682D445A794D7A5A64506E346D376B677A664D676D684836634D3363755369667938787641&valid=w7stWEQo9kGOWGQomVur8g&t=1636117922) on the browser code 404 appears.

My computer is an M1 MacBook Pro, that might have something to do with it.

Here's the output when I try to download multiple Devs episodes:

<img width="602" alt="Captura de pantalla 2021-11-05 a las 12 06 44" src="https://user-images.githubusercontent.com/40031461/140502685-c9dce69d-a2c4-46a0-aa37-de1fed633789.png">

**Comment by KevCui** [comment]
Hi @jorgeorejas, the media not found issue should be fixed in the latest commit. Please pull the changes and give it a try. Thanks.

**Comment by jorgeorejas** [comment]
Hi @KevCui, It works! Thank you!
